version: '3'
services:
  client:
    image: node:16
    
    ports:
      - 8080:8080
    
    volumes:
     - type: bind
       source: ./client_side_project_week1
       target: /code2
    working_dir: /code2

    command: bash -c "npm install && npm run dev"
    depends_on:
     - api

  api:
    image: node:18
    container_name: GTC_api
    ports:
     - 3000:3000
    
    volumes:
     - type: bind
       source: ./server_side_project_week1
       target: /code
    working_dir: /code

    command: bash -c "npm install && npm run dev"
